---
- name: prepare directories
  file: >
    state=directory
    path={{ item.path }}
    owner={{ item.owner | default(dokuwiki_user) }}
    group={{ item.group | default(dokuwiki_group) }}
    mode={{ item.mode | default('0755') }}
  with_items:
    - { path: "{{ dokuwiki_base_dir }}", owner: root, group: root }
    - { path: "{{ dokuwiki_www_dir }}", owner: root, group: root }
    - { path: "{{ dokuwiki_conf_dir }}", mode: '0750' }
    - { path: "{{ dokuwiki_data_dir }}", mode: '0750' }

- name: "symlink chrooted /log to /var/log/{{ dokuwiki_name }}"
  file: >
    state=link
    src={{ dokuwiki_logs_dir }}
    dest=/var/log/{{ dokuwiki_name }}
  when: dokuwiki_chroot_enabled


  # The aim is to exclude unwanted directories and avoid its recreating
  # on every checkout.
- name: prepare sparse git repository for dokuwiki
  shell: |
    git init
    git config core.sparsecheckout true
    git remote add origin {{ dokuwiki_source_url }}
    chdir={{ dokuwiki_www_dir }}
    creates={{ dokuwiki_www_dir }}/.git
  register: _dokuwiki_init

- name: configure sparse-checkout for dokuwiki
  copy: >
    dest={{ dokuwiki_www_dir }}/.git/info/sparse-checkout
    content='{{ dokuwiki_sparsecheckout | join("\n") }}'

- name: clone dokuwiki source repository
  git: >
    repo={{ dokuwiki_source_url }}
    version={{ dokuwiki_source_rev }}
    dest={{ dokuwiki_www_dir }}
    accept_hostkey=yes
  register: _dokuwiki_clone

  # FIXME detect changes and set changed_when
- name: symlink dist configs to the conf directory
  shell: |
    ln -rs "{{ dokuwiki_www_dir }}"/conf/* "{{ dokuwiki_conf_dir }}/" || true

- name: install plugins from git repositories
  git: >
    repo={{ item.url }}
    version={{ item.version | default('HEAD') }}
    dest={{ dokuwiki_www_dir }}/lib/plugins/{{ item.name }}
  with_items: dokuwiki_plugins
